/**
 * @author: Laye
 * @date: Creation: 28/05/2018
 * @description: class de teste de ChartRisqueController
 */
@isTest
public class ChartRisqueController_Test {
	@testSetup
    static void setUp(){        
    }
    
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test de findEntites
     */
    @isTest
    static void findEntites_TEST(){
        String methodName='findEntites';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test de findEntites
     */
    @isTest
    static void findRisques_TEST(){
        String methodName='findRisques';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test de findCategorieRisques
     */
    @isTest
    static void findCategorieRisques_TEST(){
        String methodName='findCategorieRisques';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test de risqueByCategorie
     */
    @isTest
    static void risqueByCategorie_TEST(){
        String methodName='risqueByCategorie';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test de risqueByEntiteAnnee
     */
    @isTest
    static void risqueByEntiteAnnee_TEST(){
        String methodName='risqueByEntiteAnnee';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test de risqueByEntiteAnnee
     */
    @isTest
    static void risqueByUser_TEST(){
        String methodName='risqueByUser';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
	
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test de risqueAssocieProcessusByEntite
     */
    @isTest
    static void risqueAssocieProcessusByEntite_TEST(){
        String methodName='risqueAssocieProcessusByEntite';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test de risqueEntiteByRisque
     */
    @isTest
    static void risqueEntiteByRisque_TEST(){
        String methodName='risqueEntiteByRisque';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test d'entiteAffecteeByRisque
     */
    @isTest
    static void entiteAffecteeByRisque_TEST(){
        String methodName='entiteAffecteeByRisque';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 28/05/2018
     * @description: methode de test de risqueEntiteByCotationByEntite
     */
    @isTest
    static void risqueEntiteByCotationByEntite_TEST(){
        String methodName='risqueEntiteByCotationByEntite';
        System.debug('### start- '+methodName);
        
        System.debug('### end- '+methodName);
    }
}