/**
 * @author: Laye
 * @date: Creation: 29/05/2018
 * @description: class de test de ParamRisqueEntiteController
 */
@isTest
public class ParamRisqueEntiteController_Test {
	@testSetup
    static void setUp(){        
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @description: methode de test de findFromEntite
     */
    @isTest
    static void findFromEntite_Test(){
        String methodName='findFromEntite';
        System.debug('### start- '+methodName);        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @description: methode de test d'add
     */
    @isTest
    static void add_Test(){
        String methodName='add';
        System.debug('### start- '+methodName);        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @description: methode de test de remove
     */
    @isTest
    static void remove_Test(){
        String methodName='remove';
        System.debug('### start- '+methodName);        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @description: methode de test de getElementById
     */
    @isTest
    static void getRisques_Test(){
        String methodName='getRisques';
        System.debug('### start- '+methodName);        
        System.debug('### end- '+methodName);
    }
}