/**
 * @author: Laye
 * @date: Creation: 29/05/2018
 * @description: class de test de RisqueEntiteManagement
 */
@isTest
public class RisqueEntiteManagement_Test {
	@testSetup
    static void setUp(){        
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @description: methode de test de getMesurePreventionRisqueEntite
     */
    @isTest
    static void getMesurePreventionRisqueEntite_Test(){
        String methodName='getMesurePreventionRisqueEntite';
        System.debug('### start- '+methodName);        
        System.debug('### end- '+methodName);
    }
    
    /**
     * @author: Laye
     * @date: Creation: 29/05/2018
     * @description: methode de test de getImpactRisqueEntite
     */
    @isTest
    static void getImpactRisqueEntite_Test(){
        String methodName='getImpactRisqueEntite';
        System.debug('### start- '+methodName);        
        System.debug('### end- '+methodName);
    }
    
}